// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlLI8NZlKAQMEYNkPDJHa9_fQpY6aJSPE',
    appId: '1:237200109009:web:c712d2e5f55ef5358c44f0',
    messagingSenderId: '237200109009',
    projectId: 'fcm1-12d87',
    authDomain: 'fcm1-12d87.firebaseapp.com',
    storageBucket: 'fcm1-12d87.firebasestorage.app',
    measurementId: 'G-KKGZW8LGYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUtfS6ADltidqn58ZZF0syaB3zMwHvVA4',
    appId: '1:237200109009:android:137f0a823683e6cc8c44f0',
    messagingSenderId: '237200109009',
    projectId: 'fcm1-12d87',
    storageBucket: 'fcm1-12d87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiz-WkQdw0PtKIHNwDp-FdPGpCqhbm424',
    appId: '1:237200109009:ios:cd90a66ec58511958c44f0',
    messagingSenderId: '237200109009',
    projectId: 'fcm1-12d87',
    storageBucket: 'fcm1-12d87.firebasestorage.app',
    iosBundleId: 'com.example.healthApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiz-WkQdw0PtKIHNwDp-FdPGpCqhbm424',
    appId: '1:237200109009:ios:cd90a66ec58511958c44f0',
    messagingSenderId: '237200109009',
    projectId: 'fcm1-12d87',
    storageBucket: 'fcm1-12d87.firebasestorage.app',
    iosBundleId: 'com.example.healthApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlLI8NZlKAQMEYNkPDJHa9_fQpY6aJSPE',
    appId: '1:237200109009:web:23c4c05372f9beb48c44f0',
    messagingSenderId: '237200109009',
    projectId: 'fcm1-12d87',
    authDomain: 'fcm1-12d87.firebaseapp.com',
    storageBucket: 'fcm1-12d87.firebasestorage.app',
    measurementId: 'G-TQLP5W34YG',
  );
}
